"""
Configuration for DiSA-RL diffusion model.
All hyperparameters in one place for reproducibility.
"""
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ModelConfig:
    # Environment (HalfCheetah defaults — override for other envs)
    obs_dim:    int = 17
    action_dim: int = 6
    # No reward_dim — rewards handled by reward_computer.py

    # Trajectory
    trajectory_length: int = 100     # T: sub-trajectory length

    # Architecture
    # Reduced from 512/8/8 (39M) to 256/6/4 (5M)
    # 19k training trajectories cannot support 39M params — severe overfitting
    hidden_size: int   = 256
    depth:       int   = 6
    num_heads:   int   = 4           # hidden_size % num_heads == 0
    mlp_ratio:   float = 4.0

    # RoPE
    rope_theta:   float = 10_000.0   # base frequency for RoPE
    max_seq_len:  int   = 1_024      # max positions for RoPE cache

    # Conditioning
    use_return_cond:  bool  = True
    cfg_dropout_prob: float = 0.10
    mlp_dropout:      float = 0.3    # increased from 0.1 — stronger regularization

    @property
    def feature_dim(self) -> int:
        return self.obs_dim + self.action_dim   # D = 23 (no reward)

    @property
    def cond_dim(self) -> int:
        return self.obs_dim + (1 if self.use_return_cond else 0)  # 18


@dataclass
class LossConfig:
    # Per-modality flow-matching weights
    lambda_obs:    float = 1.0
    lambda_action: float = 1.0
    # No lambda_reward — rewards not generated by diffusion model

    # Temporal consistency auxiliary loss
    # Supervises first-order obs differences: ||Δobs_pred - Δobs_real||²
    lambda_temporal: float = 0.1

    # EWC regularisation (only active during online fine-tuning)
    lambda_ewc: float = 500.0    # scale relative to flow matching loss magnitude


@dataclass
class TrainingConfig:
    batch_size:   int   = 256
    lr:           float = 1e-4
    weight_decay: float = 1e-3   # increased from 1e-4 — stronger regularization
    num_steps:    int   = 300_000
    grad_clip:    float = 1.0
    ema_decay:    float = 0.9999
    warmup_steps: int   = 5_000
    save_every:   int   = 10_000
    log_every:    int   = 100
    val_every:    int   = 2_000
    num_workers:  int   = 0
    patience:     int   = 10       # early stop after N val checks without improvement
    min_delta:    float = 1e-4     # min improvement to reset patience


@dataclass
class DataConfig:
    dataset_name:      str           = "halfcheetah-medium-v2"
    data_path:         Optional[str] = None   # set to .npz to bypass d4rl
    trajectory_length: int           = 100
    stride:            int           = 50     # sliding window stride
    val_fraction:      float         = 0.05


@dataclass
class Config:
    model:    ModelConfig    = field(default_factory=ModelConfig)
    loss:     LossConfig     = field(default_factory=LossConfig)
    training: TrainingConfig = field(default_factory=TrainingConfig)
    data:     DataConfig     = field(default_factory=DataConfig)

    device:        str = "cuda"
    seed:          int = 42
    wandb_project: str = "disa-rl"
    wandb_entity:  str = ""
    exp_name:      str = "trajectory_cfm"
    output_dir:    str = "./checkpoints"

    def __post_init__(self):
        # Keep T in sync between model and data
        self.data.trajectory_length = self.model.trajectory_length